### ISSUE TITLE
[Bug Report] 在Nuxt中的服务端渲染模式下使用Indicator报错

### ISSUE THREAD

**Issue by FisherWu29** [ElemeFE/mint-ui#1256]
### Mint UI version
2.2.13

### OS/Browsers version
chrome 62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
使用"nuxt": "^1.1.1"，按需引入组件时，其他组件可以用，但是Indicator会提示
node_modules\.2.2.13@mint-ui\lib\spinner\style.css:2
.mint-spinner-snake {
^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
  at Object.206 (E:\aomi_git\aomi-pay\node_modules\.2.2.13@mint-ui\lib\indicator\index.js:266:18)

### What is Expected?
不报错

### What is actually happening?
运行报错

**Comment by xiongxt** [comment]
我也遇到了

**Comment by falstack** [comment]
have same problem
