### ISSUE TITLE
ReferenceError: Unknown plugin "other-plugin" while building

### ISSUE THREAD

**Issue by dstollie** [ElemeFE/mint-ui#284]
Im getting an error whenever I run gulp. I followed exactly whats described in the readme and searched trough the issues if but I couldnt find a solution

error:
```
ERROR in ./resources/assets/js/app.js
Module build failed: ReferenceError: Unknown plugin "other-plugin" specified in "/Users/dennisstolmeijer/Sites/my-project/.babelrc" at 0, attempted to resolve relative to "/Users/dennisstolmeijer/Sites/my-project"
    at /Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:36)
    at OptionManager.init (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at File.initOptions (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/dennisstolmeijer/Sites/my-project/node_modules/babel-loader/index.js:131:12)
```

 

### Mint UI version

2.0.2

### Device model

Chrome

### Reproduction Link

```json
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "babel-plugin-component": "^0.4.3",
    "bootstrap-sass": "^3.3.7",
    "css-loader": "^0.25.0",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^2.0",
    "vue-resource": "^1.0.2"
  },
  "dependencies": {
    "mint-ui": "^2.0.2",
    "prismjs": "^1.5.1"
  }
}

```

Gulpfile.js
```js

const elixir = require('laravel-elixir');

require('laravel-elixir-vue-2');

Elixir.ready(function () {
	Elixir.webpack.mergeConfig({
		module: {
			loaders: [
				{
					test: /\.js$/,
					loader: 'babel',
					exclude: /node_modules/
				},
				{
					test: /\.css$/,
					loader: 'style!css'
				}
			]
		}
	})
});

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(mix => {
	mix.sass('app.scss')
		.webpack('app.js');
});
```

.babelrc
```
{
  "plugins": ["other-plugin", ["component", [
    { "libraryName": "mint-ui", "style": true }
  ]]]
}
```

app.js
```js
/**
 * First we will load all of this project's JavaScript dependencies which
 * include Vue and Vue Resource. This gives a great starting point for
 * building robust, powerful web applications using Vue and Laravel.
 */


import Vue from 'vue'
import Mint from 'mint-ui';
import 'mint-ui/lib/style.css';

import 'prismjs/prism';

import Example from './components/Example.vue';
import JourneyHistory from './components/JourneyHistory.vue'

Vue.use(Mint);

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the body of the page. From here, you may begin adding components to
 * the application, or feel free to tweak this setup for your needs.
 */

const app = new Vue({
	el: '#app',
	components: {
		Example, JourneyHistory
	}
});
```

### What is actually happening?

**Comment by Leopoldthecoder** [comment]
`other plugin` in `.babelrc` is a placeholder for your other plugins, not a literal string.

In your case, please refer to this [starter-kit](https://github.com/ElementUI/element-in-laravel-starter). It's not for Mint UI, but the basic configurations should apply.
