### ISSUE TITLE
多路由使用mt-tab-container时vue-router会报错

### ISSUE THREAD

**Issue by caikeal** [ElemeFE/mint-ui#320]
### Mint UI version
v1.0.0
### Device model
Chrome v53.0.2785.101 /IOS 10 Safari。暂时试了这2个

### vue相关版本
"vue": "1.0.26",
"vue-router": "0.7.13"

### What is actually happening?
+在多个路由中，每个路由存在类似1个这种组件。切换到这些组件路由时，第一个没有问题，后面的都会报错
   ```
	<div class="register">
		<mt-navbar class="page-part" :selected.sync="selected">
			<mt-tab-item id="supplier">我是供应商</mt-tab-item>
			<mt-tab-item id="developer">我是开发商</mt-tab-item>
		</mt-navbar>

		<mt-tab-container :active.sync="selected" swipeable>
			<mt-tab-container-item id="supplier">
				<zeco-register-sup></zeco-register-sup>		
			</mt-tab-container-item>
			<mt-tab-container-item id="developer">
				<zeco-register-dev></zeco-register-dev>
			</mt-tab-container-item>
		</mt-tab-container>
	</div>
```

+具体报错信息
```
TypeError: undefined is not a function
    at getAttr (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:1158:18)
    at getBindAttr (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:1174:13)
    at Directive._setupParams (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:8382:11)
    at Directive._bind (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:8321:8)
    at linkAndCapture (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:6928:13)
    at compositeLinkFn (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:6897:16)
    at MtTabContainer.Vue._compile (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:8611:43)
    at MtTabContainer.Vue.$mount (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:9446:10)
    at MtTabContainer.Vue._init (eval at <anonymous> (http://localhost:8080/app.js:606:2), <anonymous>:2468:12)
    at MtTabContainer.Vue._init (eval at <anonymous> (http://localhost:8080/app.js:1770:2), <anonymous>:158:17)
```

**Comment by QingWei-Li** [comment]
请给一份 demo

**Comment by caikeal** [comment]
@QingWei-Li  demo：https://github.com/caikeal/demo-for-mintui

**Comment by QingWei-Li** [comment]
fixed in #333
